### ISSUE TITLE
Python 3 - learning_lab.03_interface_configuration 

### ISSUE THREAD

**Issue by NathanCisco** [CiscoDevNet/cosc-learning-labs#19]
Running  learning_lab.03_interface_configuration with Python 3 resulted in this error.

cosc authentication url: https://198.18.1.25/controller-auth
cosc authentication parameters:
...
cosc authentication status code: 201
Python Library Documentation: function interface_configuration_tuple in module basics.interface

interface_configuration_tuple(device_name, interface_name=None)
    Return a named tuple containing the configuration information for the specified interface of the specified, mounted device.

Traceback (most recent call last):
  File "/Users/nsowatsk/git/cosc-learning-labs/src/learning_lab/03_interface_configuration.py", line 49, in <module>
    main()
  File "/Users/nsowatsk/git/cosc-learning-labs/src/learning_lab/03_interface_configuration.py", line 40, in main
    mgmt_name = management_interface(device_name)
  File "/Users/nsowatsk/git/cosc-learning-labs/src/basics/interface.py", line 57, in management_interface
    control = device_control(device_name)
  File "/Users/nsowatsk/git/cosc-learning-labs/src/basics/inventory.py", line 103, in device_control
    response = odl_http_get(_url_connector, {'node-id':device_name}, 'application/xml', expected_status_code=[200, 404])
  File "/Users/nsowatsk/git/cosc-learning-labs/src/basics/odl_http.py", line 153, in odl_http_get
    return odl_http_request('get', url_suffix, url_params, contentType, content, accept, expected_status_code)
  File "/Users/nsowatsk/git/cosc-learning-labs/src/basics/odl_http.py", line 105, in odl_http_request
    url = url.format(**{k:url_encode(v) for k, v in url_params.iteritems()})
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by kjarrad** [comment]
Fixed by issue #17
