### ISSUE TITLE
dynamic http content

### ISSUE THREAD

**Issue by kjarrad** [CiscoDevNet/cosc-learning-labs#24]
We have tried to use simple text templates for http request content/body/payload. See below for an example. This is not sophisticated enough for content where the presence of fields is dynamic. The relevant fields in the example are: shutdown, description, address, netmask - all of which can be present or absent. Note that in the example the field shutdown is absent.

Proposal: build a Python dict dynamically then convert to text using a utilty function from the JSON module.

Why is this happening now? It was always a problem for interfaces with no address so we excluded them from the sample code (as a temporary workaround). With the introduction of a new topology in dcloud we now find that the interfaces are configured differently and rather than dig deeper it is time to get out of the hole.

```
{
  "interface-configuration": [
    {
      "active": "%s",
      "Cisco-IOS-XR-ipv4-io-cfg:ipv4-network": {
        "addresses": {
          "primary": {
            "netmask": "%s", 
            "address": "%s"
          }
        }
      },%s
      "interface-name": "%s", 
      "description": "%s"
    }
  ]
}
```

**Comment by NathanCisco** [comment]
./03_interface_configuration_update.py 
cosc authentication url: https://198.18.1.25/controller-auth
cosc authentication parameters:
   username = admin
   scope = sdn
   password = cisco123
   grant_type = password
cosc authentication status code: 201
Python Library Documentation: function interface_configuration_update in module basics.interface

interface_configuration_update(device_name, interface_name, description, address, netmask, active=u'act', shutdown=False)
    Update the configuration of the specified interface of the specified device.
    
    The outcome is undefined if the specified device is not connected.

Initial configuration:
InterfaceConfiguration(name='GigabitEthernet0/0/0/2', description=None, shutdown=False, address='54.0.0.26', netmask='255.255.255.0', packet_filter_outbound=None, packet_filter_inbound=None, active='act')

Modify configuration:
interface_configuration_update(por, GigabitEthernet0/0/0/2, Mutable, 101.101.101.101, 255.255.0.0, True)

Modified configuration:
InterfaceConfiguration(name='GigabitEthernet0/0/0/2', description='Mutable', shutdown=True, address='101.101.101.101', netmask='255.255.0.0', packet_filter_outbound=None, packet_filter_inbound=None, active='act')

Restore configuration:
interface_configuration_update(por, GigabitEthernet0/0/0/2, None, 54.0.0.26, 255.255.255.0, False)

Restored configuration:
InterfaceConfiguration(name='GigabitEthernet0/0/0/2', description='None', shutdown=False, address='54.0.0.26', netmask='255.255.255.0', packet_filter_outbound=None, packet_filter_inbound=None, active='act')
Traceback (most recent call last):
  File "./03_interface_configuration_update.py", line 91, in <module>
    sys_exit(main())
  File "./03_interface_configuration_update.py", line 85, in main
    demonstrate(device_name, interface_config)
  File "./03_interface_configuration_update.py", line 69, in demonstrate
    assert restored.description == initial.description, "Expected '%s' %s got '%s' %s" % (initial.description, type(initial.description), restored.description, type(restored.description))
AssertionError: Expected 'None' <type 'NoneType'> got 'None' <type 'str'>
cisco@ubuntu:~/git/cosc-learning-labs/src/learning_lab$

**Comment by kjarrad** [comment]
03_interface_configuration_update.py now works.

TODO: other HTTP PUT/POST requests such as 
* ACL
* static routes
* device mount

**Comment by kjarrad** [comment]
static routes work completed.
just ACL work outstanding.
