### ISSUE TITLE
./04_static_route_delete.py  - AttributeError: 'str' object has no attribute '_version' in Python 2

### ISSUE THREAD

**Issue by NathanCisco** [CiscoDevNet/cosc-learning-labs#36]
./04_static_route_delete.py 
cosc authentication url: https://198.18.1.25/controller-auth
cosc authentication parameters:
   username = admin
   scope = sdn
   password = cisco123
   grant_type = password
cosc authentication status code: 201
Python Library Documentation: function static_route_delete in module basics.routes

static_route_delete(device_name, destination_network)
    Delete the specified 'static route' from the specified device.
    
    No value is returned.
    An exception is raised if the static route does not exist on the device.

inventory_static_route()
	 ['por', 'lax', 'sjc', 'sfc', 'min', 'sea', 'san', 'kcy']

static_route_list(por)
	 ['11.11.4.0/24']

static_route_delete(por, 11.11.4.0/24)
Traceback (most recent call last):
  File "./04_static_route_delete.py", line 59, in <module>
    sys_exit(main())
  File "./04_static_route_delete.py", line 54, in main
    if demonstrate(device_name):
  File "./04_static_route_delete.py", line 40, in demonstrate
    static_route_delete(device_name, destination_network)
  File "/home/cisco/git/cosc-learning-labs/src/basics/routes.py", line 113, in static_route_delete
    response = odl_http_delete(_static_route_uni_url_template, url_params, expected_status_code=[200, 500])
  File "/home/cisco/git/cosc-learning-labs/src/basics/odl_http.py", line 186, in odl_http_delete
    return odl_http_request('delete', url_suffix, url_params, contentType, content, accept, expected_status_code)
  File "/home/cisco/git/cosc-learning-labs/src/basics/odl_http.py", line 102, in odl_http_request
    url = url.format(**{k:url_encode(v) for k, v in url_params.items()})
  File "/home/cisco/git/cosc-learning-labs/src/basics/odl_http.py", line 102, in <dictcomp>
    url = url.format(**{k:url_encode(v) for k, v in url_params.items()})
  File "/home/cisco/git/cosc-learning-labs/src/basics/cosc_http.py", line 24, in <lambda>
    double_url_encode = lambda val: single_url_encode(single_url_encode(val))
  File "/usr/lib/python2.7/urllib.py", line 1292, in quote_plus
    if ' ' in s:
  File "/usr/local/lib/python2.7/dist-packages/ipaddress.py", line 705, in __contains__
    if self._version != other._version:
AttributeError: 'str' object has no attribute '_version'

**Comment by NathanCisco** [comment]
Now seeing:

cosc authentication url: https://198.18.1.25/controller-auth
...
cosc authentication status code: 201
Python Library Documentation: function static_route_delete in module basics.routes

static_route_delete(device_name, destination_network)
    Delete the specified 'static route' from the specified device.
    
    No value is returned.
    An exception is raised if the static route does not exist on the device.

inventory_static_route()
	 ['por', 'lax', 'sjc', 'sfc', 'min', 'sea', 'san', 'kcy']

static_route_list(por)
	 ['54.0.0.0/24', '11.11.4.0/24']

static_route_delete(por, 54.0.0.0/24)
Traceback (most recent call last):
  File "/Users/nsowatsk/git/cosc-learning-labs/src/learning_lab/04_static_route_delete.py", line 59, in <module>
    sys_exit(main())
  File "/Users/nsowatsk/git/cosc-learning-labs/src/learning_lab/04_static_route_delete.py", line 54, in main
    if demonstrate(device_name):
  File "/Users/nsowatsk/git/cosc-learning-labs/src/learning_lab/04_static_route_delete.py", line 40, in demonstrate
    static_route_delete(device_name, destination_network)
  File "/Users/nsowatsk/git/cosc-learning-labs/src/basics/routes.py", line 113, in static_route_delete
    response = odl_http_delete(_static_route_uni_url_template, url_params, expected_status_code=[200, 500])
  File "/Users/nsowatsk/git/cosc-learning-labs/src/basics/odl_http.py", line 190, in odl_http_delete
    return odl_http_request('delete', url_suffix, url_params, contentType, content, accept, expected_status_code)
  File "/Users/nsowatsk/git/cosc-learning-labs/src/basics/odl_http.py", line 131, in odl_http_request
    raise Exception(msg)
Exception: Expected HTTP status code [200, 500], got 404, "{
    "errors": {
        "error": [
            {
                "error-type": "protocol",
                "error-tag": "data-missing",
                "error-message": "Missing key for list \\\"vrf-prefix\\\"."
            }
        ]
    }
}"

**Comment by kjarrad** [comment]
The ip address and netmask are two separate parameters but were being encoded as one parameter.
