### ISSUE TITLE
 ./04_static_route_json.py Python 2 and 3

### ISSUE THREAD

**Issue by NathanCisco** [CiscoDevNet/cosc-learning-labs#39]
Python 3

cosc authentication url: https://198.18.1.25/controller-auth
...
cosc authentication status code: 201
Python Library Documentation: function static_route_json in module basics.routes

static_route_json(device_name, destination_network)
    JSON representation of the specified 'static route' on the specified network device.
    
    Return None if not found.

Traceback (most recent call last):
  File "/Users/nsowatsk/git/cosc-learning-labs/src/learning_lab/04_static_route_json.py", line 57, in <module>
    sys_exit(main())
  File "/Users/nsowatsk/git/cosc-learning-labs/src/learning_lab/04_static_route_json.py", line 47, in main
    inventory = inventory_static_route()
  File "/Users/nsowatsk/git/cosc-learning-labs/src/basics/routes.py", line 42, in inventory_static_route
    device_name=device_name)
  File "/Users/nsowatsk/git/cosc-learning-labs/src/basics/inventory.py", line 305, in capability_discovery
    results = etree.parse(BytesIO(response.content), parser=parser)
  File "lxml.etree.pyx", line 3310, in lxml.etree.parse (src/lxml/lxml.etree.c:72517)
  File "parser.pxi", line 1808, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:106174)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106403)
  File "parser.pxi", line 1716, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105194)
  File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:99876)
  File "parsertarget.pxi", line 160, in lxml.etree._TargetParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:117372)
  File "parsertarget.pxi", line 154, in lxml.etree._TargetParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:117265)
  File "lxml.etree.pyx", line 316, in lxml.etree._ExceptionContext._raise_if_stored (src/lxml/lxml.etree.c:10323)
  File "saxparser.pxi", line 498, in lxml.etree._handleSaxData (src/lxml/lxml.etree.c:111735)
  File "parsertarget.pxi", line 83, in lxml.etree._PythonSaxParserTarget._handleSaxData (src/lxml/lxml.etree.c:116224)
  File "/Users/nsowatsk/git/cosc-learning-labs/src/basics/inventory.py", line 263, in data
    parts = self.parts(capability_text)
  File "/Users/nsowatsk/git/cosc-learning-labs/src/basics/inventory.py", line 278, in parts
    match = _capability_pattern.match(entire_capability)
TypeError: can't use a string pattern on a bytes-like object

Python 2

 ./04_static_route_json.py 
cosc authentication url: https://198.18.1.25/controller-auth
...
ode: 201
Python Library Documentation: function static_route_json in module basics.routes

static_route_json(device_name, destination_network)
    JSON representation of the specified 'static route' on the specified network device.
    
    Return None if not found.

static_route_json(por, 54.0.1.0/24)
Traceback (most recent call last):
  File "./04_static_route_json.py", line 57, in <module>
    sys_exit(main())
  File "./04_static_route_json.py", line 52, in main
    if demonstrate(device_name):
  File "./04_static_route_json.py", line 37, in demonstrate
    route = static_route_json(device_name, destination_network)
  File "/home/cisco/git/cosc-learning-labs/src/basics/routes.py", line 87, in static_route_json
    response = odl_http_get(_static_route_uni_url_template, url_params, 'application/json', expected_status_code=[200, 404])
  File "/home/cisco/git/cosc-learning-labs/src/basics/odl_http.py", line 153, in odl_http_get
    return odl_http_request('get', url_suffix, url_params, contentType, content, accept, expected_status_code)
  File "/home/cisco/git/cosc-learning-labs/src/basics/odl_http.py", line 102, in odl_http_request
    url = url.format(**{k:url_encode(v) for k, v in url_params.items()})
  File "/home/cisco/git/cosc-learning-labs/src/basics/odl_http.py", line 102, in <dictcomp>
    url = url.format(**{k:url_encode(v) for k, v in url_params.items()})
  File "/home/cisco/git/cosc-learning-labs/src/basics/cosc_http.py", line 24, in <lambda>
    double_url_encode = lambda val: single_url_encode(single_url_encode(val))
  File "/usr/lib/python2.7/urllib.py", line 1292, in quote_plus
    if ' ' in s:
  File "/usr/local/lib/python2.7/dist-packages/ipaddress.py", line 705, in __contains__
    if self._version != other._version:
AttributeError: 'str' object has no attribute '_version'
cisco@ubuntu:~/git/cosc-learning-labs/src/learning_lab$

**Comment by kjarrad** [comment]
Code was modified to fix another issue and problem is not currently reproducible for Python 2.
