### ISSUE TITLE
04_static_route_delete_all  "Missing key for list \\\"vrf-prefix\\\"."

### ISSUE THREAD

**Issue by NathanCisco** [CiscoDevNet/cosc-learning-labs#57]
cosc authentication url: https://198.18.1.25/controller-auth
...
cosc authentication status code: 201
Python Library Documentation: function static_route_delete in module basics.routes

static_route_delete(device_name, destination_network)
    Delete the specified 'static route' from the specified device.
    
    No value is returned.
    An exception is raised if the static route does not exist on the device.

inventory_static_route()
	 ['por', 'lax', 'sjc', 'sfc', 'min', 'sea', 'san', 'kcy']

static_route_list(por)
	 ['54.0.0.0/24', '11.11.4.0/24']

static_route_delete(por, 54.0.0.0/24)
Traceback (most recent call last):
  File "/Users/nsowatsk/git/cosc-learning-labs/src/learning_lab/04_static_route_delete_all.py", line 63, in <module>
    sys_exit(main())
  File "/Users/nsowatsk/git/cosc-learning-labs/src/learning_lab/04_static_route_delete_all.py", line 58, in main
    if demonstrate(device_name):
  File "/Users/nsowatsk/git/cosc-learning-labs/src/learning_lab/04_static_route_delete_all.py", line 45, in demonstrate
    static_route_delete(device_name, destination_network)
  File "/Users/nsowatsk/git/cosc-learning-labs/src/basics/routes.py", line 113, in static_route_delete
    response = odl_http_delete(_static_route_uni_url_template, url_params, expected_status_code=[200, 500])
  File "/Users/nsowatsk/git/cosc-learning-labs/src/basics/odl_http.py", line 190, in odl_http_delete
    return odl_http_request('delete', url_suffix, url_params, contentType, content, accept, expected_status_code)
  File "/Users/nsowatsk/git/cosc-learning-labs/src/basics/odl_http.py", line 131, in odl_http_request
    raise Exception(msg)
Exception: Expected HTTP status code [200, 500], got 404, "{
    "errors": {
        "error": [
            {
                "error-type": "protocol",
                "error-tag": "data-missing",
                "error-message": "Missing key for list \\\"vrf-prefix\\\"."
            }
        ]
    }
}"

**Comment by kjarrad** [comment]
I fixed a problem that was introduced during the changes related to url encoding. I encode a slash that was never meant to be encoded. E.g. 10.0.0.1/24 should not have the slash encoded because it is actually two parameters not one.

The missing slash was not evident due to poor error handling by ODL. The error message in the response was ‘malformed url’ but the status code was 404 which is misleading because we also get 404 when the url is well formed and the static route is simply not there.
